final medicines = {
  'Abortion': ['Cytotec', 'Mifeprex'],
  'Accumulation of fluid in the scrotum': ['Surgery'],
  'Acute inflammation of lung': ['Deltasone', 'Medrol'],
  'Bloated belly': ['Agrocid', 'Alcid'],
  'Chronic tiredness syndrome': ['Elavil', 'Norpramin'],
  'Cold': ['Benadryl', 'Crocin'],
  'Constipation': ['Dulcolax', 'Enulose'],
  'Coronary heart disease': ['Norvasc'],
  'Depression': ['Elavil', 'Norpramin'],
  'Disturbed testicular descent': ['Detailed Checkup'],
  'Drug side effect': ['Benadryl', 'Allegra', 'Zyrtec'],
  'Erection problems': ['Adcirca', 'Levitra'],
  'Excessive feeling of fear': ['Xanax', 'Klonopin'],
  'Flu': ['Relenza', 'Tamiflu'],
  'Food poisoning': ['Pepto-Bismol', 'Imodium'],
  'German measles': ['Vaccine'],
  'Headache': ['Tylenol', 'Bufferin'],
  'Heart attack': ['Prinivil', 'Diovan'],
  'Heart racing': ['Panaron', 'Mexitil'],
  'Hernia': ['Femspas', 'Cimetin'],
  "Huntington's disease": ['Detailed Checkup'],
  'Hypersensitivity reaction': ['Benadryl', 'Allegra', 'Zyrtec'],
  'Inflammation of the brain covering membranes': ['Kantrex Solution'],
  'Inflammation of the epididymis': ['Monodox', 'Vibramycin'],
  'Inflammation of the nose and throat': ['Mucinex D'],
  'Inflammation of the prostate': ['Cipro'],
  'Inflammation of the testes': ['Monodox', 'Vibramycin'],
  'Joint infection': ['Cleocin', 'Cipro'],
  'Kidney stones': ['Zyloprim'],
  'Kissing disease': ['Detailed Checkup'],
  'Listeria infection': ['Acticlate'],
  'Loose watery stools': ['Dulcolax', 'Enulose'],
  'Lyme disease': ['Ceftin', 'Doxy 100'],
  'Malignant prostate cancer': ['Bicalutamide', 'Eligard'],
  'Menopause': ['Combipatch', 'estradiol'],
  'Menstrual cramps': ['Advil', 'Aleve'],
  'Narrowing of foreskin': ['Detailed Checkup'],
  'Obstruction of a pulmonary artery': ['Detailed Checkup'],
  'Pregnancy': ['Tylenol', 'Alavert'],
  'Reflux disease': ['Nexium Capsule', 'Prilosec OTC', 'Dexilant'],
  'Scarlet fever': ['Veetids'],
  'Shaking palsy': ['Levodopa'],
  'Sick headache': ['Tylenol', 'Bufferin'],
  'Slipped disc': ['Advil', 'Aleve'],
  'Smoking': ['Chantix'],
  'Sperm cyst': ['Detailed Checkup'],
  'Stomach bleeding': ['Zantac'],
  'Strain of the back muscles': ['Advil', 'Aleve'],
  'Torsion of testes': ['Surgery'],
  'Tubal and ovarian inflammation': ['Ticarcillin Solution', 'Sumycin'],
  'Urinary tract infection': ['Bactrim', 'Monurol']
};

class Medication {
  String disease;
  List<String> medicines;
  bool selected;

  Medication({this.disease, this.medicines, this.selected});
}
